### ISSUE TITLE
Reaching out gtfs2lc

### ISSUE THREAD

**Issue by pietercolpaert** [staeco/gtfs-stream#1]
Hi! We have common functionality at GTFS2LC: https://github.com/linkedconnections/gtfs2lc

Did you know about our repository? Could we somehow work together in the future?

**Comment by yocontra** [comment]
@pietercolpaert I hadn't heard of it but I read through the docs and didn't see any common functionality. All this library does is act as a low-level parser for GTFS and GTFS-RT feeds, doesn't do anything that gtfs2lc does to interpret the data.

Good to know it exists though - I did an extensive search of gtfs modules on npm and it didn't come up on any of my lists. Good luck with your project.

**Comment by derhuerst** [comment]
FYI: I also wrote [`gtfs-utils`](https://github.com/public-transport/gtfs-utils), which aims to be

- streaming (whenever possible),
- independent of the CSV source (just takes a readable streams),
- modular (`require` only what you need).

I'm about to add more utilities to it in [the `more` branch](https://github.com/public-transport/gtfs-utils/pull/12).

**Comment by yocontra** [comment]
@derhuerst Nice project - does it do anything with GTFS-RT?

I'm still mostly focused on keeping this a small low level parser library, and not doing much interpretation of schedule info.

I checked out your other project https://public-transport.github.io/friendly-public-transport-format/spec/ and can tell we've been running into a lot of the same problems dealing with these datasets, if there's ever any space for collaboration on tooling/specs let me know - I'm ultimately doing all of this for https://municipal.systems atm.

**Comment by linusnorton** [comment]
Hey... one more gtfs nerd here... I work on journey planning algorithms and as a result I've built up quite a few tools to manage / manipulate gtfs files: https://github.com/planarnetwork/

I'm currently working on a pan-European journey planner which is an interesting exercise in data hunting.

Anyway, I'm also happy to help out / collaborate

**Comment by pietercolpaert** [comment]
Would love to collaborate on any project that allows automating data reuse for fellow and future data hunters. From my perspective, a precondition for that to happen is that we start using RDF-like technology. That’s why I’ve been building Linked Connections. It’s a low-feature JSON-LD Web API that’s easy to host. While easy to host, the format still allows a client to do stuff like summarizing departures/arrivals or even planning routes entirely on the client-side.

My team is now building a route planner on top of data, first focused on Belgium (that’s what we currently have funding for), as an open-source javascript library that can be found here: https://planner.js.org.

I’ve been following @linusnorton and @derhuerst on github for a while now and would love to find a way to collaborate on common tooling. It stings to see we are all doing slightly different things ;-)

Should we plan a confcall to see whether we can align ourselves?

**Comment by linusnorton** [comment]
I'm happy to have a chat - my email is on my github profile

**Comment by yocontra** [comment]
Same ^

**Comment by derhuerst** [comment]
same

**Comment by samwu8912** [comment]
hey folks, I work with @contra and would love to help organize this chat (particularly as I just had to make a whole zip of the static files for a service that we don't run...)

should I assume something after 6pm London local time would be best (since it seems most of us are in Europe)?

**Comment by pietercolpaert** [comment]
Thanks for the nudge! I’ve created a doodle with a deadline next Monday in order to find a suitable moment for a confcall!

Fill it out here: https://doodle.com/poll/tqw243u7qbrkfzud
