### ISSUE TITLE
Byte order mark gets added to object keys

### ISSUE THREAD

**Issue by linusnorton** [staeco/gtfs-stream#2]
Unfortunately some feeds (e.g. [French bus](https://api.idbus.com/gtfs.zip)) have a byte order mark at the beginning of each file and this gets attached to the object key for each row.

For example, instead of the key for trips starting with `route_id`, it starts with `%EF%BB%BFroute_id`. To make matters worse `%EF%BB%BF` is not actually displayed when you console.log making it quite difficult to detect. The only give away is that the `route_id` is quoted as `'route_id'` unlike the other properties.

If you wouldn't mind running [strip-bom](https://github.com/sindresorhus/strip-bom) on the contents of each file just to make sure this doesn't happen I would be very grateful.

**Comment by yocontra** [comment]
@linusnorton Nice catch, will push a release today and add a test case.

**Comment by contra** [comment]
Published as 1.1.0

**Comment by yocontra** [comment]
Was hasty with that fix ^ but follow-up commit finishes it, and published as 1.1.1

**Comment by linusnorton** [comment]
@contra I think you may need to run `npm build` before you publish as the code in npm doesn't have the fix

**Comment by yocontra** [comment]
@linusnorton Sorry, I forgot this repo had a build step. Publishing as 1.1.2

**Comment by linusnorton** [comment]
All good now, thanks
